name: Build mod-eluna with Lua51 🌙

on:
  push:
    branches:
      - 'master'
      - 'main'
  pull_request:

jobs:
  build_lua51:
    uses: ./.github/workflows/core-build-base.yml
    with:
      lua_version: 'lua51'
